#!/bin/bash
BASEDIR=$PWD
. $BASEDIR/io.sh {{ number_inputs }} {{ number_parameters }} {{number_outputs}} "$@"
CURDIR=`pwd`
set -e
## INPUTS VARIABLES
{% if inputs -%}
{% for key, item in inputs.items() -%}
{{key}}=${INPUTS{{ loop.index  }}}
{% endfor -%}
{% endif %}

## PARAMETERS VARIABLES
{% if parameters -%}
{% for key, item in parameters.items() -%}
{{key}}=${PARAMS{{loop.index  }}}
{% endfor -%}
{% endif %}

set -xe

####### WRITE YOUR INVOCATION LINE AFTER THIS COMMENT



####### WRITE YOUR INVOCATION LINE BEFORE THIS COMMENT
set -e
cd $BASEDIR
. $BASEDIR/output.sh
