#!/bin/bash
set -xe
BASEDIR=`dirname $0`
. $BASEDIR/io.sh {{ number_inputs }} {{ number_parameters }} {{number_outputs}} "$@"
CURDIR=`pwd`

## INPUTS VARIABLES
{% for item in inputs -%}
{{item["name"]}}=${INPUTS{{ loop.index }}}
{% endfor -%}

## PARAMETERS VARIABLES
{% for item in parameters -%}
{{item["name"]}}=${PARAMS{{ loop.index }}}
{% endfor -%}

####### WRITE YOUR INVOCATION LINE AFTER THIS COMMENT



####### WRITE YOUR INVOCATION LINE BEFORE THIS COMMENT

. $BASEDIR/output.sh
