#!/bin/bash
set +x
set -e
. .colors.sh

BASEDIR=$PWD
. $BASEDIR/io.sh {{ number_inputs }} {{ number_parameters }} {{number_outputs}} "$@"
CURDIR=`pwd`
## INPUTS VARIABLES
{% if inputs -%}
{% for key, item in inputs.items() -%}
{{key}}=${INPUTS{{ loop.index  }}}
{% endfor -%}
{% endif %}

## PARAMETERS VARIABLES
{% if parameters -%}
{% for key, item in parameters.items() -%}
{{key}}=${PARAMS{{loop.index  }}}
{% endfor -%}
{% endif %}

set -xe

####### WRITE YOUR INVOCATION LINE AFTER THIS COMMENT
{{code}}

set +x
echo -e "$(c G)[success] The model has exited with code SUCCESS"
####### WRITE YOUR INVOCATION LINE BEFORE THIS COMMENT
cd $BASEDIR
. $BASEDIR/output.sh
