#!/bin/bash
BASEDIR=`dirname $0`
. $BASEDIR/io.sh {{ number_inputs }} {{ number_parameters }} {{number_outputs}} "$@"
CURDIR=`pwd`
set -e
## INPUTS VARIABLES
{% for key, item in inputs.items() -%}
{{key}}=${INPUTS{{ loop.index  }}}
{% endfor -%}


## PARAMETERS VARIABLES
{% for key, item in parameters.items() -%}
{{key}}=${PARAMS{{loop.index  }}}
{% endfor -%}
set -xe

####### WRITE YOUR INVOCATION LINE AFTER THIS COMMENT



####### WRITE YOUR INVOCATION LINE BEFORE THIS COMMENT
set -e
#. $BASEDIR/output.sh
