#!/bin/bash
set +x
set -e
. .colors.sh

BASEDIR=$PWD
. $BASEDIR/io.sh 1 0 1 "$@"
CURDIR=`pwd`
## INPUTS VARIABLES
sample_input_txt=${INPUTS1}


## PARAMETERS VARIABLES


set -xe

####### WRITE YOUR INVOCATION LINE AFTER THIS COMMENT


pushd .
python 212.py -i sample_input.txt
popd

set +x
echo -e "$(c G)[success] The model has exited with code SUCCESS"
####### WRITE YOUR INVOCATION LINE BEFORE THIS COMMENT
cd $BASEDIR
. $BASEDIR/output.sh